gui:
  title: "&8후원 상점 &7(&f캐시&7)"
  size: 54

lore:
  overlay:
    - "&7-------------------------"
    - "&a가격: &f{price}&7 캐시"
    - "&a수량: &f{amount}&7 개"
    - "&e클릭하여 구매"
    - "&7-------------------------"

messages:
  sent: "&a{to}&7에게 &f{amount}&7 캐시를 보냈습니다. 현재 잔액: &f{sender_balance}"
  incoming: "&a{from}&7님이 &f{amount}&7 캐시를 보냈습니다. 현재 잔액: &f{balance}"
  not_enough: "&c보유 캐시가 부족합니다. 현재 잔액: &f{balance}"
  cannot_self: "&c본인에게는 보낼 수 없습니다."
  invalid_amount: "&c수량은 1 이상의 정수여야 합니다."
  player_not_found: "&c플레이어 {player}를 찾을 수 없습니다."
  buy_success: "&a구매 완료! &f{amount}&7개를 &f{price}&7 캐시에 구매했습니다. 현재 잔액: &f{balance}"
  registered: "&a{slot}번 슬롯에 아이템을 등록했습니다."
  unregistered: "&a{slot}번 슬롯의 등록을 취소했습니다."
  invalid_slot: "&c슬롯은 0~53 사이여야 합니다."
  hold_item: "&c손에 들고 있는 아이템이 없습니다."
  only_player: "&c이 명령어는 플레이어만 사용할 수 있습니다."
  invalid_args: "&c사용법: {usage}"

  # Citizens 연동 메시지
  link_need_citizens: "&cCitizens 플러그인이 설치되어 있지 않아 연동할 수 없습니다."
  link_need_npc: "&cNPC ID를 지정하세요."
  link_success: "&aNPC(ID: {npcId})와 캐시상점을 연동했습니다."
  link_already: "&eNPC(ID: {npcId})는 이미 캐시상점과 연동되어 있습니다."
  link_error: "&c연동 중 오류가 발생했습니다."
  link_unlinked: "&aNPC(ID: {npcId}) 연동을 해제했습니다."
  link_not_linked: "&eNPC(ID: {npcId})는 캐시상점과 연동되어 있지 않습니다."
