name: UltimateCashShop
main: com.minkang.ultimate.cashshop.Main
version: 1.1.0
api-version: 1.16
author: Minkang
website: https://example.com
description: 캐시상점(54칸 GUI), 캐시 잔액, 캐시 지급, 후원상점 등록/취소, Citizens NPC 연동

commands:
  캐시상점:
    description: 캐시상점 열기/연동
    aliases: [cashshop, 후원상점열기]
    usage: /캐시상점 열기 | /캐시상점 연동
    permission: ultimate.cashshop.open
    permission-message: §c권한이 없습니다.
  캐시:
    description: 캐시 잔액 확인 및 지급
    aliases: [cash, 캐쉬]
    usage: /캐시 | /캐시 지급 <플레이어> <수량>
    permission: ultimate.cashshop.balance
    permission-message: §c권한이 없습니다.
  후원상점:
    description: 후원상점 등록/취소 관리
    aliases: [donateshop, 후원샵]
    usage: /후원상점 등록 <갯수> <가격(캐시)> <슬롯> | /후원상점 등록취소 <슬롯>
    permission: ultimate.cashshop.admin
    permission-message: §c관리자 명령어입니다.

permissions:
  ultimate.cashshop.open:
    default: true
  ultimate.cashshop.balance:
    default: true
  ultimate.cashshop.admin:
    default: op
