name: UltimateCashShop
main: com.minkang.ultimate.cashshop.Main
version: 1.4.0
api-version: 1.16
softdepend: [Citizens]
author: Minkang
website: https://example.com
description: 캐시상점(등록/삭제/열기), 캐시 잔액/지급/차감, Citizens NPC 연동

commands:
  캐시상점:
    description: 캐시상점 열기/등록/등록삭제/연동/연동해제
    aliases: [cashshop]
    usage: /캐시상점 열기 | /캐시상점 등록 <갯수> <가격(캐시)> <슬롯> | /캐시상점 등록삭제 <슬롯> | /캐시상점 연동 | /캐시상점 연동해제
    permission: ultimate.cashshop.open
    permission-message: §c권한이 없습니다.
  캐시:
    description: 캐시 잔액 확인 및 지급/차감(관리자)
    aliases: [cash, 캐쉬]
    usage: /캐시 | /캐시 지급 <플레이어> <수량> | /캐시 차감 <플레이어> <수량> | /캐시 보내기 <닉네임> <수량>
    permission: ultimate.cashshop.balance
    permission-message: §c권한이 없습니다.

permissions:
  ultimate.cashshop.open:
    default: true
  ultimate.cashshop.balance:
    default: true
  ultimate.cashshop.admin:
    default: op
