name: UltimateCashVoucher
main: com.minkang.ultimate.cashvoucher.VoucherPlugin
version: 1.0.0
api-version: 1.16
authors: [minkang]
website: https://example.com
description: "OP-only /캐시권 <금액> - 오른손 허공 우클릭로만 사용되는 캐시 수표 아이템 발행/사용 (UltimateCashShop 연동)"
softdepend: [UltimateCashShop]

commands:
  캐시권:
    description: "오피: 캐시 수표 발행"
    usage: "/캐시권 <금액>"
    permission: ultimate.cashshop.voucher

permissions:
  ultimate.cashshop.voucher:
    description: "캐시 수표를 발행할 수 있음 (오피)"
    default: op
